# Generated by Django 4.1.7 on 2023-02-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='accounts/default.jpg', upload_to='accounts/'),
        ),
    ]
