# Generated by Django 4.1.7 on 2023-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default="Hi, I'm beginning inventor", null=True),
        ),
    ]
