# Generated by Django 4.1.6 on 2023-02-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
