# Generated by Django 4.1.7 on 2023-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='products/default.jpg', null=True, upload_to='products/'),
        ),
    ]
