# Generated by Django 4.1.6 on 2023-02-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
