# Generated by Django 4.1.7 on 2023-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_needs_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='needs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
