# Generated by Django 4.1.4 on 2023-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producttag_alter_product_main_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='products.producttag'),
        ),
    ]
