# Generated by Django 4.1.7 on 2023-02-25 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_main_image'),
        ('products', '0007_product_tags'),
    ]

    operations = [
    ]
