# Generated by Django 4.1.4 on 2023-02-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_0007_alter_product_main_image_0007_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='how_many',
            field=models.IntegerField(null=True),
        ),
    ]
