# Generated by Django 4.1.4 on 2023-02-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_producttag_how_many'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttag',
            old_name='how_many',
            new_name='number',
        ),
    ]
